version: '3'

services:
  aquarium-microservice:
    container_name: aquarium-microservice
    build: .
    command: bash -c "yarn && yarn dev"
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/app
    network_mode: host
